#!bin/bash
#
# Startup huaban_git
#
# chkconfig: - 85 15
# description: huaban_git server，自动github push
# processname: huaban_git


RETVAL=0
dir=/root/Doc/bin/huaban

# Source function library.
. /etc/rc.d/init.d/functions

start() {
	echo "git add"
	cd $dir
	git add .
	echo "commit"
	git commit "init" | exit 0
	echo "push"
	git push | exit 0
	echo "push over"
}

case "$1" in
	start)
		start
		;;
		*)
	echo $"Usage: $0 {start}"
	exit 2
esac
exit $?