#!bin/bash
#
# Startup huaban_warm
#
# chkconfig: - 85 15
# description: huaban_warm server
# processname: huaban_warm


RETVAL=0
prog="huaban_warm"
exec=/root/Doc/bin/huaban/$prog
log=/root/Doc/log/$prog.log

# Source function library.
. /etc/rc.d/init.d/functions

start() {
	echo "启动中"
	nohup $exec > $log 2>&1 &
	echo "启动完毕"
}

stop() {
	echo "关闭中"
	killproc $prog
	echo "已经关闭"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
esac
echo "Usage: $0 {start|stop|restart}"
        exit 1
exit $?
